name: Create Issue on PR

on:
  pull_request:
    types: [opened]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "New Pull Request: ${{ github.event.pull_request.title }}"
          body: "A new pull request has been opened. Please review and provide feedback."
          assignees: octocat
          labels: "New Pull Request, enhancement"
