name: Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Build e empurre contêiner
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: danielcruzr/streamlit:discord
          build-args: |
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
      - name: Execute o contêiner
        run: |
          docker run -d -p --name stream danielcruzr/streamlit:discord
      - name: IP do contêiner
        run: |
          docker inspect stream | grep IPAddress

